# Generated by Django 4.0.5 on 2023-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SupplyChainData',
        ),
    ]
